GET http://139.59.206.3:80/properties

###
GET http://139.59.206.3:80/properties/5d9efb39ed996a162e77e26e

###

POST http://139.59.206.3:80/properties
Content-Type: application/json

{
    "name": "one",
    "location": "here",
    "geo": {
        "lat": "20",
        "lng": "30"
    }
}

###
DELETE http://139.59.206.3:80/properties

###

DELETE http://139.59.206.3:80/properties/5d9efc92ed996a162e77e273

###

PATCH http://139.59.206.3:80/properties/5d9e569455be1a3265612504
Content-Type:  application/json

{
    "name": "Three",
    "price": "5000",
    "imageUrl": "pictureURLhere"
}
