//Properties

###
GET https://178.62.11.46:21880/properties/5da22324d3ecfd0980806780
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRoaXMuY29tIiwiaWQiOiI1ZDlmYjRmYTYwNGE4YzQ4NGJkYmVhZmEiLCJhZ2VudCI6ZmFsc2UsImlhdCI6MTU3MDkxMzEwMywiZXhwIjoxNTcwOTIwMzAzfQ.SB7aYEXUyDuH_CWa15nX49DikVOSAfjb3aixbdlas4A"
}

###
GET https://178.62.11.46:21880/properties
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1c3Rpbi5hYnJhbXNAaG90bWFpbC5jb20iLCJpZCI6IjVkYTIxNzQ5YmJlN2MxMmZlMWNlMjFmOSIsImFnZW50Ijp0cnVlLCJpYXQiOjE1NzA5MDk3NzIsImV4cCI6MTU3MDk0NTc3Mn0.CcuTeAKm9JgbzcEwEZDOxnJmMj5h_gMNfS7aA--5KfE"
}

###

POST https://178.62.11.46:21880/properties
Content-Type: application/json

{
    "name": "one",
    "location": "here",
    "price": "1000",
    "geo": {
        "lat": "20",
        "lng": "30"
    },
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQHRoaXMuY29tIiwiaWQiOiI1ZDlmYjRmYTYwNGE4YzQ4NGJkYmVhZmEiLCJpYXQiOjE1NzA5MTA4MDQsImV4cCI6MTU3MDkxNDQwNH0.r6D0ZYPgSmppIeQsYImr-kLX1fwJMmRuooME3oFlOvg"
}

###

DELETE https://178.62.11.46:21880/properties/5da21d66a8dcd1014b7d2783
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1c3Rpbi5hYnJhbXNAaG90bWFpbC5jb20iLCJpZCI6IjVkYTIxNzQ5YmJlN2MxMmZlMWNlMjFmOSIsImFnZW50Ijp0cnVlLCJpYXQiOjE1NzA5MDk3NzIsImV4cCI6MTU3MDk0NTc3Mn0.CcuTeAKm9JgbzcEwEZDOxnJmMj5h_gMNfS7aA--5KfE"
}

###

PATCH https://178.62.11.46:21880/properties/5da21d66a8dcd1014b7d2783
Content-Type:  application/json

{
    "name": "Four",
    "price": "5000",
    "imageUrl": "pictureURLhere",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1c3Rpbi5hYnJhbXNAaG90bWFpbC5jb20iLCJpZCI6IjVkYTIxNzQ5YmJlN2MxMmZlMWNlMjFmOSIsImFnZW50Ijp0cnVlLCJpYXQiOjE1NzA5MDk3NzIsImV4cCI6MTU3MDk0NTc3Mn0.CcuTeAKm9JgbzcEwEZDOxnJmMj5h_gMNfS7aA--5KfE"
}

//========================================================================
//Agents

###
POST https://178.62.11.46:21880/agents/authentication
Content-Type: application/json

{
    "email": "justin.abrams@hotmail.com",
    "password": "P@ssw0rd!@#"
}

###
POST http://178.62.11.46:21870/agents
Content-Type: application/json

{
    "firstname": "1",
    "lastname": "1",
    "email": "one@1mail.com",
    "password": "one"
}

###
GET https://178.62.11.46:21880/agents
###
DELETE https://178.62.11.46:21880/agents/5d9f6c9d701c1b3a9e0ae27a

//========================================================================
//Customers

###
POST https://178.62.11.46:21880/customers/authentication
Content-Type: application/json

{
    "email": "test1@this.com",
    "password": "P@55"
}
###
POST https://178.62.11.46:21880/customers
Content-Type: application/json

{
    "firstname": "first",
    "lastname": "last",
    "email": "test1@this.com",
    "password": "P@55"
}
###
GET https://178.62.11.46:21880/customers
###
DELETE https://178.62.11.46:21880/customers/5d9f7521e2d3bd3c6c57037d
